[ new ] RRB-Vector
idris-community/idris2-containers pull request #10
Opened 2024-11-19 23:14 UTC by Matthew-Mosior

This PR adds a relaxed radix balanced vector (`rrb-vector`) implementation, ported from Haskell.

Please see the following [primary research article](https://infoscience.epfl.ch/server/api/core/bitstreams/7c8b929f-1f68-4948-8ea8-e364e4899b2a/content) about `rrb-vectors`.

This `RRBVector` implementation is very much on par with `Seq` from `Data.Seq.Unsized` in `contrib` (serves as a good basis of comparison).

`RRBVector` is faster than `Seq` for the following operations:

- `fromList`
- `lookup/index`
- `map`
- `replicate`
- `splitAt`

`RRBVector` is slower than `Seq` for the following operations:

- `cons`
- `snoc`
- `append`
- `reverse`

### Summary

Overall, I think this PR offers a solid implementation of a `rrb-vector` which gives end users a great data structure to reach for covering numerous use cases.

### Results (Profiling)

```
# 40: containers/fromListRRBVector/1
  time per run : 9.373 ns
  mean         : 18.34 ns
  r2           : 0.9999732297326667

# 41: containers/fromListRRBVector/100
  time per run : 2.280 μs
  mean         : 2.176 μs
  r2           : 0.9995320807172481

# 42: containers/fromListRRBVector/1000
  time per run : 25.83 μs
  mean         : 22.81 μs
  r2           : 0.9817888014746644

# 43: containers/fromListSeqUnsized/1
  time per run : 16.20 ns
  mean         : 25.95 ns
  r2           : 0.999521670759127

# 44: containers/fromListSeqUnsized/100
  time per run : 3.105 μs
  mean         : 3.096 μs
  r2           : 0.9992131594305628

# 45: containers/fromListSeqUnsized/1000
  time per run : 30.33 μs
  mean         : 31.13 μs
  r2           : 0.9997090235878536

# 46: containers/consRRBVector/10
  time per run : 1.242 μs
  mean         : 1.399 μs
  r2           : 0.9843260156856984

# 47: containers/consSeqUnsized/10
  time per run : 324.7 ns
  mean         : 343.8 ns
  r2           : 0.9999753549678946

# 48: containers/snocRRBVector/10
  time per run : 1.231 μs
  mean         : 1.290 μs
  r2           : 0.9998341718015606

# 49: containers/snocSeqUnsized/10
  time per run : 319.6 ns
  mean         : 356.1 ns
  r2           : 0.9998698113679716

# 50: containers/appendRRBVector/10
  time per run : 422.6 ns
  mean         : 459.6 ns
  r2           : 0.999697808856862

# 51: containers/appendSeqUnsized/10
  time per run : 266.4 ns
  mean         : 275.8 ns
  r2           : 0.999956394125627

# 52: containers/indexRRBVector/1
  time per run : 66.84 ns
  mean         : 79.90 ns
  r2           : 0.9997989980325633

# 53: containers/indexRRBVector/100
  time per run : 6.940 μs
  mean         : 6.661 μs
  r2           : 0.9999658039952234

# 54: containers/indexRRBVector/1000
  time per run : 74.80 μs
  mean         : 76.14 μs
  r2           : 0.9999833415581493

# 55: containers/indexRRBVector/10000
  time per run : 846.2 μs
  mean         : 851.0 μs
  r2           : 1.0002989778009403

# 56: containers/indexSeqUnsized/1
  time per run : 59.61 ns
  mean         : 68.36 ns
  r2           : 0.9997772012409748

# 57: containers/indexSeqUnsized/100
  time per run : 18.52 μs
  mean         : 18.65 μs
  r2           : 0.9999933754732101

# 58: containers/indexSeqUnsized/1000
  time per run : 278.9 μs
  mean         : 283.1 μs
  r2           : 1.0003311968575612

# 59: containers/indexSeqUnsized/10000
  time per run : 3.762 ms
  mean         : 3.785 ms
  r2           : 0.9999175867174286

# 60: containers/mapRRBVector/1
  time per run : 22.77 ns
  mean         : 34.57 ns
  r2           : 0.9995992965519647

# 61: containers/mapRRBVector/100
  time per run : 2.930 μs
  mean         : 2.894 μs
  r2           : 0.9994920317457673

# 62: containers/mapRRBVector/1000
  time per run : 29.07 μs
  mean         : 29.43 μs
  r2           : 0.9999753773208367

# 63: containers/mapRRBVector/10000
  time per run : 295.2 μs
  mean         : 301.9 μs
  r2           : 0.999839299231119

# 64: containers/mapSeqUnsized/1
  time per run : 16.60 ns
  mean         : 24.91 ns
  r2           : 0.9995084356862853

# 65: containers/mapSeqUnsized/100
  time per run : 2.888 μs
  mean         : 2.893 μs
  r2           : 0.9999675160503703

# 66: containers/mapSeqUnsized/1000
  time per run : 30.00 μs
  mean         : 29.70 μs
  r2           : 0.9997230614829223

# 67: containers/mapSeqUnsized/10000
  time per run : 315.5 μs
  mean         : 321.2 μs
  r2           : 1.0001624213467506

# 68: containers/replicateRRBVector/1
  time per run : 6.239 ns
  mean         : 14.25 ns
  r2           : 0.9999888009376133

# 69: containers/replicateRRBVector/100
  time per run : 58.52 ns
  mean         : 72.88 ns
  r2           : 0.9999857091931337

# 70: containers/replicateRRBVector/1000
  time per run : 122.4 ns
  mean         : 133.4 ns
  r2           : 0.9999848330428394

# 71: containers/replicateRRBVector/10000
  time per run : 122.2 ns
  mean         : 133.6 ns
  r2           : 0.9999547333064154

# 72: containers/replicateSeqUnsized/1
  time per run : 4.215 ns
  mean         : 11.35 ns
  r2           : 0.999993856946792

# 73: containers/replicateSeqUnsized/100
  time per run : 1.199 μs
  mean         : 1.217 μs
  r2           : 0.9996747163991737

# 74: containers/replicateSeqUnsized/1000
  time per run : 12.71 μs
  mean         : 12.82 μs
  r2           : 0.9999890725904093

# 75: containers/replicateSeqUnsized/10000
  time per run : 132.0 μs
  mean         : 133.6 μs
  r2           : 1.0000775220609381

# 76: containers/reverseRRBVector/1
  time per run : 12.09 ns
  mean         : 22.02 ns
  r2           : 0.9988310706666055

# 77: containers/reverseRRBVector/100
  time per run : 4.701 μs
  mean         : 4.505 μs
  r2           : 0.9994069576589218

# 78: containers/reverseRRBVector/1000
  time per run : 56.40 μs
  mean         : 56.41 μs
  r2           : 0.99996379231141

# 79: containers/reverseRRBVector/10000
  time per run : 722.8 μs
  mean         : 754.1 μs
  r2           : 1.0027284143016488

# 80: containers/reverseSeqUnsized/1
  time per run : 15.88 ns
  mean         : 27.28 ns
  r2           : 0.9965463110639334

# 81: containers/reverseSeqUnsized/100
  time per run : 2.890 μs
  mean         : 2.872 μs
  r2           : 0.9992106084258962

# 82: containers/reverseSeqUnsized/1000
  time per run : 29.43 μs
  mean         : 29.37 μs
  r2           : 0.9999909936567694

# 83: containers/reverseSeqUnsized/10000
  time per run : 313.1 μs
  mean         : 316.6 μs
  r2           : 1.000214224694908

# 84: containers/splitAtRRBVector/1
  time per run : 16.07 ns
  mean         : 25.64 ns
  r2           : 0.9999173770080869

# 85: containers/splitAtRRBVector/100
  time per run : 3.172 μs
  mean         : 3.165 μs
  r2           : 0.999514443984228

# 86: containers/splitAtRRBVector/1000
  time per run : 25.56 μs
  mean         : 25.64 μs
  r2           : 0.9995438476234718

# 87: containers/splitAtRRBVector/10000
  time per run : 252.6 μs
  mean         : 247.7 μs
  r2           : 0.9998914911764366

# 88: containers/splitAtSeqUnsized/1
  time per run : 28.08 ns
  mean         : 39.38 ns
  r2           : 0.9998585676548469

# 89: containers/splitAtSeqUnsized/100
  time per run : 3.323 μs
  mean         : 3.296 μs
  r2           : 0.9998101038622065

# 90: containers/splitAtSeqUnsized/1000
  time per run : 30.98 μs
  mean         : 31.20 μs
  r2           : 0.9999969901930207

# 91: containers/splitAtSeqUnsized/10000
  time per run : 302.8 μs
  mean         : 316.3 μs
  r2           : 1.0003139926623965
```

2024-12-07 19:27 UTC, Matthew-Mosior commented
@stefan-hoeck 

This should be ready for you whenever you have time.

2024-12-13 19:54 UTC, stefan-hoeck commented
Thanks again, for you valuable work. Having a look now.

2024-12-13 20:00 UTC, stefan-hoeck requested changes

2024-12-13 20:00 UTC, stefan-hoeck commented on containers.ipkg
> +           , contrib
Why do we need a dependency on contrib? I'm sorry, but I try to remove contrib from all of my projects, so this dependency will have to go.

2024-12-13 20:02 UTC, stefan-hoeck commented
I'm afraid this is currently way over my head. I'll be happy to merge this, but can't comment on it in detail. It would be great to have some documentation / tutorial / use cases for this data structure: When and why is it useful?

Also: Several function such as `lookup` are annotated with `partial`. Are these indeed partial (for instance: `lookup` returns a `Maybe`). Do we want to have such an unsafe API, or can this be improved?

2024-12-13 20:21 UTC, Matthew-Mosior commented
> I'm afraid this is currently way over my head. I'll be happy to merge this, but can't comment on it in detail. It would be great to have some documentation / tutorial / use cases for this data structure: When and why is it useful?
> 
> Also: Several function such as `lookup` are annotated with `partial`. Are these indeed partial (for instance: `lookup` returns a `Maybe`). Do we want to have such an unsafe API, or can this be improved?

`rrb-vectors` are a very similar data structure to `sequences`.  They have slightly better performance for indexing/lookups (almost match that of `array`s) than sequences, where in contrast `sequences` are slightly faster at cons/snocs.  They are a very useful data structure that in many cases can replace a vector/array where you want an easier to use API.

As far as the `partial` functions, not sure if/how that can be addressed. Many of those functions are more of less ports from https://hackage.haskell.org/package/rrb-vector, and don't may not have good opportunities to write them such that they satisfy the totality checker via correct structural recursion.

2024-12-13 20:24 UTC, Matthew-Mosior commented on containers.ipkg
> +           , contrib
The only need for `contrib` is access to `Data.Seq.Unsized` for means of bench-marking (provides a good basis of comparison).

2024-12-13 20:25 UTC, Matthew-Mosior commented on containers.ipkg
> +           , contrib
@stefan-hoeck 

I would be happy to move the `Data.Seq.Unsized`/`Data.Seq.Sized` code into this repo, do you think I should do that in this PR to avoid pulling in `contrib`?

2024-12-13 20:41 UTC, Matthew-Mosior commented on containers.ipkg
> +           , contrib
@stefan-hoeck 

I've moved `Data.Seq.Internal`, Data.Seq.Sized` and `Data.Seq.Unsized` from `contrib` to here (this should be fine to do, right?).

2024-12-13 23:20 UTC, Matthew-Mosior commented
> I'm afraid this is currently way over my head. I'll be happy to merge this, but can't comment on it in detail. It would be great to have some documentation / tutorial / use cases for this data structure: When and why is it useful?
> 
> Also: Several function such as `lookup` are annotated with `partial`. Are these indeed partial (for instance: `lookup` returns a `Maybe`). Do we want to have such an unsafe API, or can this be improved?

@stefan-hoeck 

The numerous `partial` annotations have been addressed via 85eb81dc6df52f4a58df33136838521b40134135.

2024-12-14 09:22 UTC, stefan-hoeck commented on containers.ipkg
> +           , contrib
If the dependency on contrib is only for profiling, it should be added as a dependency to the `profile/profile.ipkg` file. There it would be perfectly acceptable since this would not add a transitive dependency on contrib to downstream libraries. That would be the preferrable way of handling this in my opinion.

2024-12-14 09:30 UTC, stefan-hoeck commented
> The numerous `partial` annotations have been addressed via [85eb81d](https://github.com/stefan-hoeck/idris2-containers/commit/85eb81dc6df52f4a58df33136838521b40134135).

Yes, using `covering` is the way to go here unless we expect a function to fail with a runtime exception. Feel free to also use `assert_total` or `assert_smaller` if you are certain that a function will not loop forever.

2024-12-14 14:37 UTC, Matthew-Mosior commented
> > The numerous `partial` annotations have been addressed via [85eb81d](https://github.com/stefan-hoeck/idris2-containers/commit/85eb81dc6df52f4a58df33136838521b40134135).
> 
> Yes, using `covering` is the way to go here unless we expect a function to fail with a runtime exception. Feel free to also use `assert_total` or `assert_smaller` if you are certain that a function will not loop forever.

No functions here are expected to fail with a runtime exception.  I'll work on marking with `assert_smaller`/`assert_total` since none of these functions are expected to loop forever either.

2024-12-16 05:19 UTC, Matthew-Mosior commented
> > > The numerous `partial` annotations have been addressed via [85eb81d](https://github.com/stefan-hoeck/idris2-containers/commit/85eb81dc6df52f4a58df33136838521b40134135).
> > 
> > 
> > Yes, using `covering` is the way to go here unless we expect a function to fail with a runtime exception. Feel free to also use `assert_total` or `assert_smaller` if you are certain that a function will not loop forever.
> 
> No functions here are expected to fail with a runtime exception. I'll work on marking with `assert_smaller`/`assert_total` since none of these functions are expected to loop forever either.

@stefan-hoeck 

This is addressed via 42d785ac36dfb576b465cb64d203c47d43c876f5.  Should be ready to look at again.

2024-12-16 16:54 UTC, Matthew-Mosior commented on containers.ipkg
> +           , contrib
@stefan-hoeck 

Do you have an opinion one way or another of moving `contrib`'s `Seq` into this repo?  I think it would be nice to move as much of that code out of `contrib` as possible, if and when it makes sense (which in this case I believe it does).

2024-12-17 17:28 UTC, Matthew-Mosior commented
@stefan-hoeck

Wanted to check in and see if there was anything else needed before merging this PR.

2024-12-28 21:30 UTC, Matthew-Mosior commented
@stefan-hoeck 

I'm going to try to move this `RRBVector` to a `MArray` (versus the current `Array` based) implementation.

2025-01-09 17:31 UTC, Matthew-Mosior commented
I think it makes sense to merge this in as is, and then can optimize with `MArray`s later on.

2025-01-09 17:35 UTC, merged