[ new] Map
idris-community/idris2-containers pull request #3
Opened 2024-08-23 22:03 UTC by Matthew-Mosior

This PR adds a finite map implementation, mainly ported from Haskell.

2024-08-24 03:58 UTC, stefan-hoeck requested changes

2024-08-24 03:58 UTC, stefan-hoeck commented on src/Data/Map/Internal.idr
> +Size = Int
Please don't use `Int`: It has different bit sizes on different backends and is the slowest integer type on the default Chez backend. If you want to get decent performance on scheme and JavaScript, use `Bits32` (because `Size` is non-negative, right?). If you can live with slightly slower performance on JavaScript, use `Nat` for best performance on scheme backends.

2024-08-24 04:00 UTC, stefan-hoeck commented
Thanks for this! One question: How does this perform compared with `Data.SortedMap` in base, which is also a self-balancing sorted tree using `Ord` for the keys?

2024-08-24 04:36 UTC, Matthew-Mosior commented on src/Data/Map/Internal.idr
> +Size = Int
Great catch, I didn't remember this nuance when deciding on `Int` vs `Nat`.  I've updated the code to use `Nat` anywhere `Int` was used previously.

2024-08-24 04:37 UTC, Matthew-Mosior commented
> Thanks for this! One question: How does this perform compared with `Data.SortedMap` in base, which is also a self-balancing sorted tree using `Ord` for the keys?

I haven't thoroughly tested yet, but will certainly do so, and report back here.

2024-09-14 22:51 UTC, Matthew-Mosior commented
@stefan-hoeck 

I've added `profile` (`ikpg`) which benchmarks this new `Map` vs. `SortedMap` from `contrib`.

**Summary**:

This `Map` implementation is very much on par (if not a bit more performant) with `SortedMap` in terms of performance.

`Map` and `SortedMap` are on par for the following operations:
- `delete`

`Map` is faster than `SortedMap` for the following operations:
- `fromList` (most likely stemming from a preliminary sorting test prior to generating the internal tree)
- `update`
- `lookup `
- `keys`
- `values`

`Map` is slower than `SortedMap` for the following operation:
- `insert`

Overall, I think this `Map` implementation is a solid implementation of a map/dictionary data structure that can provide great utility for many use cases.

**Results**:

```
# 1: map/List/1
  time per run : 12.68 ns
  mean         : 38.57 ns
  r2           : 0.999498977119776


# 2: map/List/100
  time per run : 1.375 μs
  mean         : 1.294 μs
  r2           : 0.9999871439836611


# 3: map/List/1000
  time per run : 13.29 μs
  mean         : 13.81 μs
  r2           : 0.9997045459204021


# 4: map/fromListMap/1
  time per run : 21.16 ns
  mean         : 38.06 ns
  r2           : 0.9999613944868838


# 5: map/fromListMap/100
  time per run : 6.359 μs
  mean         : 6.202 μs
  r2           : 0.9992873188167132


# 6: map/fromListMap/1000
  time per run : 76.71 μs
  mean         : 77.28 μs
  r2           : 0.995732845638674


# 7: map/fromListSortedMap/1
  time per run : 27.78 ns
  mean         : 46.59 ns
  r2           : 0.9999714790551445


# 8: map/fromListSortedMap/100
  time per run : 13.69 μs
  mean         : 13.28 μs
  r2           : 0.9999329843643512


# 9: map/fromListSortedMap/1000
  time per run : 202.2 μs
  mean         : 205.9 μs
  r2           : 1.0001521503169504


# 10: map/insertMap/10
  time per run : 1.954 μs
  mean         : 1.981 μs
  r2           : 0.9999839505702541


# 11: map/insertSortedMap/10
  time per run : 469.6 ns
  mean         : 497.5 ns
  r2           : 0.9999058012896355


# 12: map/deleteMap/10
  time per run : 1.156 μs
  mean         : 1.111 μs
  r2           : 0.9998932183303313


# 13: map/deleteSortedMap/10
  time per run : 995.1 ns
  mean         : 994.8 ns
  r2           : 0.99994187392901


# 14: map/updateMap/10
  time per run : 1.085 μs
  mean         : 1.123 μs
  r2           : 0.9999662485765402


# 15: map/updateSortedMap/10
  time per run : 1.682 μs
  mean         : 1.701 μs
  r2           : 0.9999866665611727


# 16: map/lookupMap/10
  time per run : 509.8 ns
  mean         : 514.9 ns
  r2           : 0.9999450907764993


# 17: map/lookupSortedMap/10
  time per run : 590.6 ns
  mean         : 614.1 ns
  r2           : 0.9999313407493803


# 18: map/keysMap/1000000
  time per run : 391.1 ms
  mean         : 400.8 ms
  r2           : 0.9997691822562049


# 19: map/keysSortedMap/1000000
  time per run : 640.8 ms
  mean         : 652.5 ms
  r2           : 0.999636752905979


# 20: map/valuesMap/1000000
  time per run : 399.3 ms
  mean         : 399.0 ms
  r2           : 0.9993409088337426


# 21: map/valuesSortedMap/1000000
  time per run : 651.4 ms
  mean         : 660.8 ms
  r2           : 0.9998605765381943
```

2024-09-19 00:54 UTC, Matthew-Mosior commented
@stefan-hoeck

This should be ready for you to look at when you have a chance.

2024-09-19 04:08 UTC, stefan-hoeck requested changes

2024-09-19 04:08 UTC, stefan-hoeck commented on src/Data/Map.idr
> +    EQ => x
This is not a total function, because it can crash at runtime when the key is not in the map. We must therefore not use `assert_total` here: `assert_total` is for those cases where we know (and can proof) that a function is total but have no other way to convince Idris. This function should be `partial`.

2024-09-19 04:13 UTC, stefan-hoeck commented
This is incredible and really, really cool. The API is huge, and it's clean code and well documented. Thank you so much for doing this. I did not yet have the time to look at the whol thing in detail, (it's *a lot* of code), but I'm deeply impressed by the thoroughness of it.

We should have some tests for this, but I suggest the following: We should soon merge this as it is, and then we can set up some property tests in a later PR. That way, CI will run automatically, without me always clicking the "approve" button. I can setup some basic Hedgehog tests if you haven't used those before, but for some of the more intricate functions it will make sense if you come up with some test cases of your own.

Again, this is huge, so thank you very much for your contribution!

2024-09-19 13:17 UTC, Matthew-Mosior commented on src/Data/Map.idr
> +    EQ => x
@stefan-hoeck 

Awesome catch here, I totally forgot to add those annotations, they should be added now via https://github.com/stefan-hoeck/idris2-containers/pull/3/commits/5586d97076f82737095fabdf825fc00cadfea433.

2024-09-19 13:21 UTC, Matthew-Mosior commented
> This is incredible and really, really cool. The API is huge, and it's clean code and well documented. Thank you so much for doing this. I did not yet have the time to look at the whol thing in detail, (it's _a lot_ of code), but I'm deeply impressed by the thoroughness of it.
> 
> We should have some tests for this, but I suggest the following: We should soon merge this as it is, and then we can set up some property tests in a later PR. That way, CI will run automatically, without me always clicking the "approve" button. I can setup some basic Hedgehog tests if you haven't used those before, but for some of the more intricate functions it will make sense if you come up with some test cases of your own.
> 
> Again, this is huge, so thank you very much for your contribution!

You're welcome, really glad I could  help contribute this!  I'm very excited by the prospect of having these data structures at our disposal now.

That sounds great, this should be in a good place to merge as of now (barring any linting issues).  I really like the idea of setting up a CI pipeline, and I would definitely be interested in helping write some of the more nuanced tests.

2024-09-19 13:36 UTC, Matthew-Mosior commented
@stefan-hoeck 

Linting issues should be fixed now.

2024-09-24 22:42 UTC, Matthew-Mosior commented
@stefan-hoeck 

Wanted to check in and see if there was anything else needed before merging this PR.

2024-09-25 04:53 UTC, stefan-hoeck approved these changes

2024-09-25 04:53 UTC, stefan-hoeck commented
Sorry for the delay. And once again: Thanks for adding this. It looks really well designed and documented.

2024-09-25 04:53 UTC, merged

2024-09-25 14:21 UTC, Matthew-Mosior commented
> Sorry for the delay. And once again: Thanks for adding this. It looks really well designed and documented.

No worries at all!  Very excited for this PR.